spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydemo?useUnicode=true&characterEncoding=utf8&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: root
  ## QQ邮箱配置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1750514326@qq.com #发送邮件的邮箱地址
    password:  kwacamrmpfeabbjf #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1750514326@qq.com # 发送邮件的地址，和上面username一致
    #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

# 注意
# 126邮箱SMTP服务器地址:smtp.126.com,端口号:465或者994
# 163邮箱SMTP服务器地址:smtp.163.com,端口号:465或者994
# yeah邮箱SMTP服务器地址:smtp.yeah.net,端口号:465或者994


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.zjc.demo.dao: debug










